import { TaskState } from "../../types/tasks/task";

export const initialState: TaskState = {
    tasks: [
        {
            _id: '1',
            title: 'Have to run',
            description: 'I will be running in the morning for 10 to 20 min to keep myself fit',
            priority: 'Urgent',
            status: "To Do",
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2021-09-01').toISOString(),
        },
        {
            _id: '2',
            title: 'Do Daily Task',
            description: 'Will make a list of tasks to be done today',
            priority: 'Urgent',
            status: 'In Progress',
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2025-09-02').toISOString(),
        },
        {
            _id: '3',
            title: 'Eat Healthy',
            description: 'Will eat healthy food to keep myself fit',
            priority: 'Urgent',
            status: 'In Progress',
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2021-09-03').toISOString(),
        },
        {
            _id: '4',
            title: 'Do workout',
            description: 'Have to do workout in the evening for 1 hour',
            priority: 'Urgent',
            status: 'Finished',
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2025-09-04').toISOString(),
        },
        {
            _id: '5',
            title: 'Danish to be called',
            description: 'Call Danish to discuss about the project, And also discuss about the future plans',
            priority: 'Urgent',
            status: 'To Do',
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2025-09-05').toISOString(),
        },
        {
            _id: '6',
            title: 'Task 6',
            description: 'Description 6',
            priority: 'Urgent',
            status: 'To Do',
            logs: [],
            comments: [],
            subTasks: [],
            createdAt: new Date('2021-09-06').toISOString(),
        },
    ]
};
